society1 = Society.create! :name => 'Samarth Aangan CHS', :number_of_flats => 330, :active => true, :society_address_line1 => 'Lokhandwala Complex, K.L.walawalkar road', :society_address_line2 => 'Andheri West', :society_pincode => '400053'
society2 = Society.create! :name => 'Oshiwara ind. Center', :number_of_flats => 270, :active => true, :society_address_line1 => 'Link Road Opp Oshiwara Bus depo', :society_address_line2 => 'Goregaon West', :society_pincode => '400104'
society3 = Society.create! :name => 'BRIGHOTN TOWER CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1, :active => true, :number_of_flats => 120
society4 = Society.create! :name => 'AARAM NAGAR CHS',:society_address_line1 => '',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1, :active => true, :number_of_flats => 120
society5 = Society.create! :name => 'AASHIRWAD CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society6 = Society.create! :name => 'ACCORD CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society7 = Society.create! :name => 'ACROPOLIS CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society8 = Society.create! :name => 'AKSHARDHAM CHS',:society_address_line1 => 'VERSOVA MHADA',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society9 = Society.create! :name => 'AMIT ESTATE CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society10 = Society.create! :name => 'APNA GHAR SWATI CHS',:society_address_line1 => '1ST CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society11 = Society.create! :name => 'ARENA CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society12 = Society.create! :name => 'ASHISH (RBI)CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society13 = Society.create! :name => 'WOOD ROSE CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society14 = Society.create! :name => 'TRISHUL CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society15 = Society.create! :name => 'ATLAS SKYWALKER CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society16 = Society.create! :name => 'TROIKA APT CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society17 = Society.create! :name => 'BALLERINA CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society18 = Society.create! :name => 'BASERA CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society19 = Society.create! :name => 'BELMONT CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society20 = Society.create! :name => 'BELSCOT CHS',:society_address_line1 => 'OPP KAMAT CLUB',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society21 = Society.create! :name => 'BENHUR CHS',:society_address_line1 => 'OPP KAMAT CLUB',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society22 = Society.create! :name => 'BENZER CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society23 = Society.create! :name => 'TWIN TOWER CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society24 = Society.create! :name => 'BREEZE CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society25 = Society.create! :name => 'VENUS CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society26 = Society.create! :name => 'BRIGHTON BUNGLOW CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society27 = Society.create! :name => 'BROOKHILL TOWER CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society28 = Society.create! :name => 'WEST WIND CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society29 = Society.create! :name => 'CITIZEN CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society30 = Society.create! :name => 'CLARIDGE CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society31 = Society.create! :name => 'CLIFF TOWER CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society32 = Society.create! :name => 'CONCORD CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society33 = Society.create! :name => 'COSMOS CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society34 = Society.create! :name => 'CROSS GATE CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society35 = Society.create! :name => 'DENZIL CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society36 = Society.create! :name => 'WINCHESTER CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society37 = Society.create! :name => 'STERLING TOWER CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society38 = Society.create! :name => 'EDEN WOODS CHS',:society_address_line1 => 'SHASTRI NAGAR',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society39 = Society.create! :name => 'EXCELLENCY CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society40 = Society.create! :name => 'GALACTICA CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society41 = Society.create! :name => 'GARDEN VIEW CHS',:society_address_line1 => 'SHASTRI NAGAR',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society42 = Society.create! :name => 'SUMAN APT CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society43 = Society.create! :name => 'SUMAN TOWER CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society44 = Society.create! :name => 'GREEN ACRES CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society45 = Society.create! :name => 'SUN SWEPT CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society46 = Society.create! :name => 'GREEN VILLE CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society47 = Society.create! :name => 'GREEN FIELD CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society48 = Society.create! :name => 'SUNNY SIDE CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society49 = Society.create! :name => 'GURU DARSHAN CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society50 = Society.create! :name => 'GURU KRUPA CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society51 = Society.create! :name => 'GURU PRASAD CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society52 = Society.create! :name => 'GURUDARSHAN  CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society53 = Society.create! :name => 'HARMONY CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society54 = Society.create! :name => 'HERITAGE CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society55 = Society.create! :name => 'HIGHLAND PARK CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society56 = Society.create! :name => 'HOME COURT CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society57 = Society.create! :name => 'HOME LAND CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society58 = Society.create! :name => 'HOME STEAD CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society59 = Society.create! :name => 'SUNSWEPT CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society60 = Society.create! :name => 'SYMPHONY CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society61 = Society.create! :name => 'SANTOSH TOWER CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society62 = Society.create! :name => 'IVORY HEIGHT CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society63 = Society.create! :name => 'JUPITER CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society64 = Society.create! :name => 'SARANGA TOWER CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society65 = Society.create! :name => 'SEA SHELL CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society66 = Society.create! :name => 'SHEFFEILD TOWER CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society67 = Society.create! :name => 'KEN MORE CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society68 = Society.create! :name => 'KENWOOD CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society69 = Society.create! :name => 'KINGSTON CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society70 = Society.create! :name => 'SILVER SPRING CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society71 = Society.create! :name => 'KRYSTAL AVENUE CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society72 = Society.create! :name => 'LEGEND CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society73 = Society.create! :name => 'LENNIE CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society74 = Society.create! :name => 'SKY LARK CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society75 = Society.create! :name => 'SKY WALKER CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society76 = Society.create! :name => 'SPRING FIELD CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society77 = Society.create! :name => 'STELLAR TOWER CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society78 = Society.create! :name => 'MAGNAM TOWER CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society79 = Society.create! :name => 'MAGNUM BUNGLOW CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society80 = Society.create! :name => 'PRERNA CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society81 = Society.create! :name => 'PRIME ROSE CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society82 = Society.create! :name => 'MANJU TOWER CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society83 = Society.create! :name => 'MEDHAVI CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society84 = Society.create! :name => 'MEGHDOOD  CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society85 = Society.create! :name => 'MERCURY CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society86 = Society.create! :name => 'REGENCY CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society87 = Society.create! :name => 'RAINANSANCE CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society88 = Society.create! :name => 'RESIDENCY CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society89 = Society.create! :name => 'MONISHA TOWER CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society90 = Society.create! :name => 'MONTANA CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society91 = Society.create! :name => 'MOTA MAHAL CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society92 = Society.create! :name => 'MOTA MANSION CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society93 = Society.create! :name => 'NAV KARAN CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society94 = Society.create! :name => 'NEBULA CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society95 = Society.create! :name => 'NEPTUNE CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society96 = Society.create! :name => 'NESTLE CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society97 = Society.create! :name => 'NORWOOD CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society98 = Society.create! :name => 'NUTAN  ABHISHEK CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society99 = Society.create! :name => 'OBEROI SKY GARDEN CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society100 = Society.create! :name => 'OBEROI SKY HEIGHTS CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society101 = Society.create! :name => 'OBEROI SKY LARK CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society102 = Society.create! :name => 'RICHMOND CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society103 = Society.create! :name => 'RIYA PALACE CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society104 = Society.create! :name => 'RNA ARCADE CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society105 = Society.create! :name => 'ROHIT APT CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society106 = Society.create! :name => 'PADMAVATI APT CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society107 = Society.create! :name => 'PALM SPRING CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society108 = Society.create! :name => 'PANORAMA TOWER CHS',:society_address_line1 => '4TH CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society109 = Society.create! :name => 'PEARL APT CHS',:society_address_line1 => '3RD CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society110 = Society.create! :name => 'RUSHI TOWER CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society111 = Society.create! :name => 'PREMIUM TOWER CHS',:society_address_line1 => 'MAIN ROAD',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society112 = Society.create! :name => 'SAMARTH  KRUPA CHS',:society_address_line1 => 'LOKHANDWALA COMPLEX',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
society113 = Society.create! :name => 'ABHISHEK CHS',:society_address_line1 => '2ND CROSS LANE',:society_address_line2 => 'ANDHERI (W)', :society_city => 'MUMBAI',:society_pincode => '400053', :active => true, :number_of_flats => 1
