puts 'SETTING UP DEFAULT USER LOGIN'
user = User.create! :name => 'First User', :email => 'user@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :super_admin

user = User.create! :name => 'society_admin', :email => 'society_admin@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :society_admin
user = User.create! :name => 'society_team', :email => 'society_team@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :society_team
user = User.create! :name => 'society_manager', :email => 'society_manager@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :society_manager

user = User.create! :name => 'First User', :email => 'user@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :super_admin

user = User.create! :name => 'society_admin', :email => 'society_admin@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :society_admin
user = User.create! :name => 'society_team', :email => 'society_team@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :society_team
user = User.create! :name => 'society_manager', :email => 'society_manager@example.com', :password => 'please', :password_confirmation => 'please', :confirmed_at => Time.now.utc
puts 'New user created: ' << user.name
user.add_role :society_manager



society1 = Society.create! :name => 'Samarth Angan CHS', :number_of_flats => 330, :active => true, :society_address_line1 => 'Lokhandwala Complex, K.L.walawalkar road', :society_address_line2 => 'Andheri West', :society_pincode => '400053'
society2 = Society.create! :name => 'Oshiwara ind. Center', :number_of_flats => 270, :active => true, :society_address_line1 => 'Link Road Opp Oshiwara Bus depo', :society_address_line2 => 'Goregaon West', :society_pincode => '400104'
society3 = Society.create! :name => 'Brighton Tower CHS', :number_of_flats => 120, :active => true, :society_address_line1 => 'Lokhandwala Complex, 2nd cross lane', :society_address_line2 => 'Andheri West', :society_pincode => '400053'
puts 'New society created: ' 
 unit1 = Unit.create! :unit_number => '1502', :wing_name => 'A', :building_name => '1', :floor_name => '15', :unit_type_id => 7, :society_id => 2
 unit1 = Unit.create! :unit_number => '1501', :wing_name => 'A', :building_name => '1', :floor_name => '15', :unit_type_id => 7, :society_id => 2
 unit1 = Unit.create! :unit_number => '1402', :wing_name => 'A', :building_name => '1', :floor_name => '14', :unit_type_id => 7, :society_id => 2
 unit1 = Unit.create! :unit_number => '1401', :wing_name => 'A', :building_name => '1', :floor_name => '14', :unit_type_id => 7, :society_id => 2
 unit1 = Unit.create! :unit_number => '1302', :wing_name => 'A', :building_name => '1', :floor_name => '13', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '1301', :wing_name => 'A', :building_name => '1', :floor_name => '13', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '1202', :wing_name => 'A', :building_name => '1', :floor_name => '12', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '1201', :wing_name => 'A', :building_name => '1', :floor_name => '12', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '1102', :wing_name => 'A', :building_name => '1', :floor_name => '11', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '1101', :wing_name => 'A', :building_name => '1', :floor_name => '11', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '1002', :wing_name => 'A', :building_name => '1', :floor_name => '10', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '1001', :wing_name => 'A', :building_name => '1', :floor_name => '10', :unit_type_id => 8, :society_id => 3
 unit1 = Unit.create! :unit_number => '501', :wing_name => 'A', :building_name => '1', :floor_name => '5', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '502', :wing_name => 'A', :building_name => '1', :floor_name => '5', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '503', :wing_name => 'A', :building_name => '1', :floor_name => '5', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '504', :wing_name => 'A', :building_name => '1', :floor_name => '5', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '505', :wing_name => 'A', :building_name => '1', :floor_name => '5', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '506', :wing_name => 'A', :building_name => '1', :floor_name => '5', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '601', :wing_name => 'A', :building_name => '1', :floor_name => '6', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '602', :wing_name => 'A', :building_name => '1', :floor_name => '6', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '603', :wing_name => 'A', :building_name => '1', :floor_name => '6', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '604', :wing_name => 'A', :building_name => '1', :floor_name => '6', :unit_type_id => 10, :society_id => 2
 unit1 = Unit.create! :unit_number => '605', :wing_name => 'A', :building_name => '1', :floor_name => '6', :unit_type_id => 10, :society_id => 2
puts 'New units for society 2 & 3 created: ' 
      Unit.create(:unit_number => '1702',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1701',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1705',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1706',:wing_name => 'B',:building_name => '1',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1603',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1604',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1602',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1601',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1605',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1606',:wing_name => 'B',:building_name => '1',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1503',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1504',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1502',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1501',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1505',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1506',:wing_name => 'B',:building_name => '1',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1403',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1404',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1402',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1401',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1405',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1406',:wing_name => 'B',:building_name => '1',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1303',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1304',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1302',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1301',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1305',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1306',:wing_name => 'B',:building_name => '1',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1203',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1204',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1202',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1201',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1205',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1206',:wing_name => 'B',:building_name => '1',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1103',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1104',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1102',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1101',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1105',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1106',:wing_name => 'B',:building_name => '1',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1003',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1004',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1002',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1001',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1005',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1006',:wing_name => 'B',:building_name => '1',:floor_name => '10',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1803',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1804',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1802',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1801',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1805',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1806',:wing_name => 'B',:building_name => '1',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1903',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1904',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1902',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1901',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1905',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1906',:wing_name => 'B',:building_name => '1',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2003',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2004',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2005',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2006',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2002',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '2001',:wing_name => 'B',:building_name => '1',:floor_name => '20',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '101',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '102',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '103',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '104',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '105',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '106',:wing_name => 'B',:building_name => '1',:floor_name => '1',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '201',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '202',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '203',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '204',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '205',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '206',:wing_name => 'B',:building_name => '1',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '301',:wing_name => 'B',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '302',:wing_name => 'B',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '303',:wing_name => 'B',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '304',:wing_name => 'B',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '305',:wing_name => 'B',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '306',:wing_name => 'B',:building_name => '1',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '401',:wing_name => 'B',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '402',:wing_name => 'B',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '403',:wing_name => 'B',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '404',:wing_name => 'B',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '405',:wing_name => 'B',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '406',:wing_name => 'B',:building_name => '1',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '501',:wing_name => 'B',:building_name => '1',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '502',:wing_name => 'B',:building_name => '1',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '503',:wing_name => 'B',:building_name => '1',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '504',:wing_name => 'B',:building_name => '1',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '505',:wing_name => 'B',:building_name => '1',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '506',:wing_name => 'B',:building_name => '1',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '601',:wing_name => 'B',:building_name => '1',:floor_name => '6',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '602',:wing_name => 'B',:building_name => '1',:floor_name => '6',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '603',:wing_name => 'B',:building_name => '1',:floor_name => '6',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '604',:wing_name => 'B',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '605',:wing_name => 'B',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '606',:wing_name => 'B',:building_name => '1',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '701',:wing_name => 'B',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '702',:wing_name => 'B',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '703',:wing_name => 'B',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '704',:wing_name => 'B',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '705',:wing_name => 'B',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '706',:wing_name => 'B',:building_name => '1',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '801',:wing_name => 'B',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '802',:wing_name => 'B',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '803',:wing_name => 'B',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '804',:wing_name => 'B',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '805',:wing_name => 'B',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '806',:wing_name => 'B',:building_name => '1',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '901',:wing_name => 'B',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '902',:wing_name => 'B',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '903',:wing_name => 'B',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '904',:wing_name => 'B',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '905',:wing_name => 'B',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '906',:wing_name => 'B',:building_name => '1',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '1703',:wing_name => 'A',:building_name => '2',:floor_name => '17',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '1704',:wing_name => 'A',:building_name => '2',:floor_name => '17',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1702',:wing_name => 'A',:building_name => '2',:floor_name => '17',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1701',:wing_name => 'A',:building_name => '2',:floor_name => '17',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1705',:wing_name => 'A',:building_name => '2',:floor_name => '17',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1706',:wing_name => 'A',:building_name => '2',:floor_name => '17',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1603',:wing_name => 'A',:building_name => '2',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1604',:wing_name => 'A',:building_name => '2',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1602',:wing_name => 'A',:building_name => '2',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1601',:wing_name => 'A',:building_name => '2',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1605',:wing_name => 'A',:building_name => '2',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1606',:wing_name => 'A',:building_name => '2',:floor_name => '16',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1503',:wing_name => 'A',:building_name => '2',:floor_name => '15',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1504',:wing_name => 'A',:building_name => '2',:floor_name => '15',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1502',:wing_name => 'A',:building_name => '2',:floor_name => '15',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1501',:wing_name => 'A',:building_name => '2',:floor_name => '15',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1505',:wing_name => 'A',:building_name => '2',:floor_name => '15',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1506',:wing_name => 'A',:building_name => '2',:floor_name => '15',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1403',:wing_name => 'A',:building_name => '2',:floor_name => '14',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1404',:wing_name => 'A',:building_name => '2',:floor_name => '14',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1402',:wing_name => 'A',:building_name => '2',:floor_name => '14',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1401',:wing_name => 'A',:building_name => '2',:floor_name => '14',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1405',:wing_name => 'A',:building_name => '2',:floor_name => '14',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1406',:wing_name => 'A',:building_name => '2',:floor_name => '14',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1303',:wing_name => 'A',:building_name => '2',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1304',:wing_name => 'A',:building_name => '2',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1302',:wing_name => 'A',:building_name => '2',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1301',:wing_name => 'A',:building_name => '2',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1305',:wing_name => 'A',:building_name => '2',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1306',:wing_name => 'A',:building_name => '2',:floor_name => '13',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1203',:wing_name => 'A',:building_name => '2',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1204',:wing_name => 'A',:building_name => '2',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1202',:wing_name => 'A',:building_name => '2',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1201',:wing_name => 'A',:building_name => '2',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1205',:wing_name => 'A',:building_name => '2',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1206',:wing_name => 'A',:building_name => '2',:floor_name => '12',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1103',:wing_name => 'A',:building_name => '2',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1104',:wing_name => 'A',:building_name => '2',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1102',:wing_name => 'A',:building_name => '2',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1101',:wing_name => 'A',:building_name => '2',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1105',:wing_name => 'A',:building_name => '2',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1106',:wing_name => 'A',:building_name => '2',:floor_name => '11',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1003',:wing_name => 'A',:building_name => '2',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1004',:wing_name => 'A',:building_name => '2',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1002',:wing_name => 'A',:building_name => '2',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1001',:wing_name => 'A',:building_name => '2',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1005',:wing_name => 'A',:building_name => '2',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1006',:wing_name => 'A',:building_name => '2',:floor_name => '10',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1803',:wing_name => 'A',:building_name => '2',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1804',:wing_name => 'A',:building_name => '2',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1802',:wing_name => 'A',:building_name => '2',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1801',:wing_name => 'A',:building_name => '2',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1805',:wing_name => 'A',:building_name => '2',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1806',:wing_name => 'A',:building_name => '2',:floor_name => '18',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1903',:wing_name => 'A',:building_name => '2',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1904',:wing_name => 'A',:building_name => '2',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1902',:wing_name => 'A',:building_name => '2',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1901',:wing_name => 'A',:building_name => '2',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1905',:wing_name => 'A',:building_name => '2',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '1906',:wing_name => 'A',:building_name => '2',:floor_name => '19',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2003',:wing_name => 'A',:building_name => '2',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2004',:wing_name => 'A',:building_name => '2',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2005',:wing_name => 'A',:building_name => '2',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2006',:wing_name => 'A',:building_name => '2',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2002',:wing_name => 'A',:building_name => '2',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '2001',:wing_name => 'A',:building_name => '2',:floor_name => '20',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '101',:wing_name => 'A',:building_name => '2',:floor_name => '1',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '102',:wing_name => 'A',:building_name => '2',:floor_name => '1',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '103',:wing_name => 'A',:building_name => '2',:floor_name => '1',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '104',:wing_name => 'A',:building_name => '2',:floor_name => '1',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '105',:wing_name => 'A',:building_name => '2',:floor_name => '1',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '106',:wing_name => 'A',:building_name => '2',:floor_name => '1',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '201',:wing_name => 'A',:building_name => '2',:floor_name => '2',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '202',:wing_name => 'A',:building_name => '2',:floor_name => '2',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '203',:wing_name => 'A',:building_name => '2',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '204',:wing_name => 'A',:building_name => '2',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '205',:wing_name => 'A',:building_name => '2',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '206',:wing_name => 'A',:building_name => '2',:floor_name => '2',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '301',:wing_name => 'A',:building_name => '2',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '302',:wing_name => 'A',:building_name => '2',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '303',:wing_name => 'A',:building_name => '2',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '304',:wing_name => 'A',:building_name => '2',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '305',:wing_name => 'A',:building_name => '2',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '306',:wing_name => 'A',:building_name => '2',:floor_name => '3',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '401',:wing_name => 'A',:building_name => '2',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '402',:wing_name => 'A',:building_name => '2',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '403',:wing_name => 'A',:building_name => '2',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '404',:wing_name => 'A',:building_name => '2',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '405',:wing_name => 'A',:building_name => '2',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '406',:wing_name => 'A',:building_name => '2',:floor_name => '4',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '501',:wing_name => 'A',:building_name => '2',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '502',:wing_name => 'A',:building_name => '2',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '503',:wing_name => 'A',:building_name => '2',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '504',:wing_name => 'A',:building_name => '2',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '505',:wing_name => 'A',:building_name => '2',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '506',:wing_name => 'A',:building_name => '2',:floor_name => '5',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '601',:wing_name => 'A',:building_name => '2',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '602',:wing_name => 'A',:building_name => '2',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '603',:wing_name => 'A',:building_name => '2',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '604',:wing_name => 'A',:building_name => '2',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '605',:wing_name => 'A',:building_name => '2',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '606',:wing_name => 'A',:building_name => '2',:floor_name => '6',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '701',:wing_name => 'A',:building_name => '2',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '702',:wing_name => 'A',:building_name => '2',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '703',:wing_name => 'A',:building_name => '2',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '704',:wing_name => 'A',:building_name => '2',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '705',:wing_name => 'A',:building_name => '2',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '706',:wing_name => 'A',:building_name => '2',:floor_name => '7',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '801',:wing_name => 'A',:building_name => '2',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '802',:wing_name => 'A',:building_name => '2',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '803',:wing_name => 'A',:building_name => '2',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '804',:wing_name => 'A',:building_name => '2',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '805',:wing_name => 'A',:building_name => '2',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '806',:wing_name => 'A',:building_name => '2',:floor_name => '8',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '901',:wing_name => 'A',:building_name => '2',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '902',:wing_name => 'A',:building_name => '2',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '903',:wing_name => 'A',:building_name => '2',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '904',:wing_name => 'A',:building_name => '2',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '905',:wing_name => 'A',:building_name => '2',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '906',:wing_name => 'A',:building_name => '2',:floor_name => '9',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '1703',:wing_name => 'B',:building_name => '2',:floor_name => '17',:unit_type_id => 10,:society_id => 1)
      Unit.create(:unit_number => '1704',:wing_name => 'B',:building_name => '2',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1702',:wing_name => 'B',:building_name => '2',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1701',:wing_name => 'B',:building_name => '2',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1705',:wing_name => 'B',:building_name => '2',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1706',:wing_name => 'B',:building_name => '2',:floor_name => '17',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1603',:wing_name => 'B',:building_name => '2',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1604',:wing_name => 'B',:building_name => '2',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1602',:wing_name => 'B',:building_name => '2',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1601',:wing_name => 'B',:building_name => '2',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1605',:wing_name => 'B',:building_name => '2',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1606',:wing_name => 'B',:building_name => '2',:floor_name => '16',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1503',:wing_name => 'B',:building_name => '2',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1504',:wing_name => 'B',:building_name => '2',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1502',:wing_name => 'B',:building_name => '2',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1501',:wing_name => 'B',:building_name => '2',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1505',:wing_name => 'B',:building_name => '2',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1506',:wing_name => 'B',:building_name => '2',:floor_name => '15',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1403',:wing_name => 'B',:building_name => '2',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1404',:wing_name => 'B',:building_name => '2',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1402',:wing_name => 'B',:building_name => '2',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1401',:wing_name => 'B',:building_name => '2',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1405',:wing_name => 'B',:building_name => '2',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1406',:wing_name => 'B',:building_name => '2',:floor_name => '14',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1303',:wing_name => 'B',:building_name => '2',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1304',:wing_name => 'B',:building_name => '2',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1302',:wing_name => 'B',:building_name => '2',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1301',:wing_name => 'B',:building_name => '2',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1305',:wing_name => 'B',:building_name => '2',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1306',:wing_name => 'B',:building_name => '2',:floor_name => '13',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1203',:wing_name => 'B',:building_name => '2',:floor_name => '12',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1204',:wing_name => 'B',:building_name => '2',:floor_name => '12',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1202',:wing_name => 'B',:building_name => '2',:floor_name => '12',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1201',:wing_name => 'B',:building_name => '2',:floor_name => '12',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1205',:wing_name => 'B',:building_name => '2',:floor_name => '12',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1206',:wing_name => 'B',:building_name => '2',:floor_name => '12',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1103',:wing_name => 'B',:building_name => '2',:floor_name => '11',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1104',:wing_name => 'B',:building_name => '2',:floor_name => '11',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1102',:wing_name => 'B',:building_name => '2',:floor_name => '11',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1101',:wing_name => 'B',:building_name => '2',:floor_name => '11',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1105',:wing_name => 'B',:building_name => '2',:floor_name => '11',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1106',:wing_name => 'B',:building_name => '2',:floor_name => '11',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1003',:wing_name => 'B',:building_name => '2',:floor_name => '10',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1004',:wing_name => 'B',:building_name => '2',:floor_name => '10',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1002',:wing_name => 'B',:building_name => '2',:floor_name => '10',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1001',:wing_name => 'B',:building_name => '2',:floor_name => '10',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1005',:wing_name => 'B',:building_name => '2',:floor_name => '10',:unit_type_id => 11,:society_id => 1)
      Unit.create(:unit_number => '1006',:wing_name => 'B',:building_name => '2',:floor_name => '10',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '1803',:wing_name => 'B',:building_name => '2',:floor_name => '18',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1804',:wing_name => 'B',:building_name => '2',:floor_name => '18',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1802',:wing_name => 'B',:building_name => '2',:floor_name => '18',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1801',:wing_name => 'B',:building_name => '2',:floor_name => '18',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1805',:wing_name => 'B',:building_name => '2',:floor_name => '18',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1806',:wing_name => 'B',:building_name => '2',:floor_name => '18',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1903',:wing_name => 'B',:building_name => '2',:floor_name => '19',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1904',:wing_name => 'B',:building_name => '2',:floor_name => '19',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1902',:wing_name => 'B',:building_name => '2',:floor_name => '19',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1901',:wing_name => 'B',:building_name => '2',:floor_name => '19',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1905',:wing_name => 'B',:building_name => '2',:floor_name => '19',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '1906',:wing_name => 'B',:building_name => '2',:floor_name => '19',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '2003',:wing_name => 'B',:building_name => '2',:floor_name => '20',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '2004',:wing_name => 'B',:building_name => '2',:floor_name => '20',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '2005',:wing_name => 'B',:building_name => '2',:floor_name => '20',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '2006',:wing_name => 'B',:building_name => '2',:floor_name => '20',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '2002',:wing_name => 'B',:building_name => '2',:floor_name => '20',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '2001',:wing_name => 'B',:building_name => '2',:floor_name => '20',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '101',:wing_name => 'B',:building_name => '2',:floor_name => '1',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '102',:wing_name => 'B',:building_name => '2',:floor_name => '1',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '103',:wing_name => 'B',:building_name => '2',:floor_name => '1',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '104',:wing_name => 'B',:building_name => '2',:floor_name => '1',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '105',:wing_name => 'B',:building_name => '2',:floor_name => '1',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '106',:wing_name => 'B',:building_name => '2',:floor_name => '1',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '201',:wing_name => 'B',:building_name => '2',:floor_name => '2',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '202',:wing_name => 'B',:building_name => '2',:floor_name => '2',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '203',:wing_name => 'B',:building_name => '2',:floor_name => '2',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '204',:wing_name => 'B',:building_name => '2',:floor_name => '2',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '205',:wing_name => 'B',:building_name => '2',:floor_name => '2',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '206',:wing_name => 'B',:building_name => '2',:floor_name => '2',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '301',:wing_name => 'B',:building_name => '2',:floor_name => '3',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '302',:wing_name => 'B',:building_name => '2',:floor_name => '3',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '303',:wing_name => 'B',:building_name => '2',:floor_name => '3',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '304',:wing_name => 'B',:building_name => '2',:floor_name => '3',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '305',:wing_name => 'B',:building_name => '2',:floor_name => '3',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '306',:wing_name => 'B',:building_name => '2',:floor_name => '3',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '401',:wing_name => 'B',:building_name => '2',:floor_name => '4',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '402',:wing_name => 'B',:building_name => '2',:floor_name => '4',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '403',:wing_name => 'B',:building_name => '2',:floor_name => '4',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '404',:wing_name => 'B',:building_name => '2',:floor_name => '4',:unit_type_id => 7,:society_id => 1)
      Unit.create(:unit_number => '405',:wing_name => 'B',:building_name => '2',:floor_name => '4',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '406',:wing_name => 'B',:building_name => '2',:floor_name => '4',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '501',:wing_name => 'B',:building_name => '2',:floor_name => '5',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '502',:wing_name => 'B',:building_name => '2',:floor_name => '5',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '503',:wing_name => 'B',:building_name => '2',:floor_name => '5',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '504',:wing_name => 'B',:building_name => '2',:floor_name => '5',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '505',:wing_name => 'B',:building_name => '2',:floor_name => '5',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '506',:wing_name => 'B',:building_name => '2',:floor_name => '5',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '601',:wing_name => 'B',:building_name => '2',:floor_name => '6',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '602',:wing_name => 'B',:building_name => '2',:floor_name => '6',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '603',:wing_name => 'B',:building_name => '2',:floor_name => '6',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '604',:wing_name => 'B',:building_name => '2',:floor_name => '6',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '605',:wing_name => 'B',:building_name => '2',:floor_name => '6',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '606',:wing_name => 'B',:building_name => '2',:floor_name => '6',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '701',:wing_name => 'B',:building_name => '2',:floor_name => '7',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '702',:wing_name => 'B',:building_name => '2',:floor_name => '7',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '703',:wing_name => 'B',:building_name => '2',:floor_name => '7',:unit_type_id => 8,:society_id => 1)
      Unit.create(:unit_number => '704',:wing_name => 'B',:building_name => '2',:floor_name => '7',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '705',:wing_name => 'B',:building_name => '2',:floor_name => '7',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '706',:wing_name => 'B',:building_name => '2',:floor_name => '7',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '801',:wing_name => 'B',:building_name => '2',:floor_name => '8',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '802',:wing_name => 'B',:building_name => '2',:floor_name => '8',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '803',:wing_name => 'B',:building_name => '2',:floor_name => '8',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '804',:wing_name => 'B',:building_name => '2',:floor_name => '8',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '805',:wing_name => 'B',:building_name => '2',:floor_name => '8',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '806',:wing_name => 'B',:building_name => '2',:floor_name => '8',:unit_type_id => 9,:society_id => 1)
      Unit.create(:unit_number => '901',:wing_name => 'B',:building_name => '2',:floor_name => '9',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '902',:wing_name => 'B',:building_name => '2',:floor_name => '9',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '903',:wing_name => 'B',:building_name => '2',:floor_name => '9',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '904',:wing_name => 'B',:building_name => '2',:floor_name => '9',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '905',:wing_name => 'B',:building_name => '2',:floor_name => '9',:unit_type_id => 6,:society_id => 1)
      Unit.create(:unit_number => '906',:wing_name => 'B',:building_name => '2',:floor_name => '9',:unit_type_id => 6,:society_id => 1)
puts 'New units for society 1 created: ' 
 member = Member.create! :mobile_phone => "0000000000", :name => "Name No", :society_id => 1
 member = Member.create! :mobile_phone => "9843707178", :name => "chandrakant Jain", :society_id => 2
 member = Member.create! :mobile_phone => "9543707178", :name => "User Example",  :society_id => 3
 member = Member.create! :mobile_phone => "9343707178", :name => "Sharmila Raone", :society_id => 2
 member = Member.create! :mobile_phone => "9443707178", :name => "Ujwal Jain", :society_id => 2
 member = Member.create! :mobile_phone => "9911736445", :name => "SUDHAKAR PATEL", :society_id => 3
 member = Member.create! :mobile_phone => "9811736445", :name => "Nitin Witsel", :society_id => 3
 member = Member.create! :mobile_phone => "9711736445", :name => "ABUZAR Defour", :society_id => 3
 member = Member.create! :mobile_phone => "9611736445", :name => "Reginal Patel", :society_id => 3
 member = Member.create! :mobile_phone => "9111736445", :name => "Nirmala GUPTA",   :society_id => 2
 member = Member.create! :mobile_phone => "9711736445", :name => "Laxminarayan De Camargo", :society_id => 3
puts 'New members created: ' 
#puts 'New user created: ' << user.username
